<?
$dance_titles = array('20030726' => 'Dan &amp; Kathy Koft Calling and Cueing',
					  '20011111' => '2001 Mini Festival',
					  '20021110' => '2002 Mini Festival',
				        '19981108' => '1998 Mini Festival',
					  '19991114' => '1999 Mini Festival',
					  '20031109' => '2003 Mini Festival',
					  '20031031' => 'Halloween -- Nick Martellacci Calling',
					  '19981031' => '40th Anniversary &amp; Halloween');
$club = 'NNJSDA Dances';
?>